# Generated by Django 5.0.2 on 2024-02-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatheHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('weather_date', models.DateField(auto_now_add=True)),
                ('weather_data', models.TextField(blank=True, null=True)),
                ('forecast_data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='weathehistory',
            constraint=models.UniqueConstraint(fields=('location', 'weather_date'), name='location day constraint'),
        ),
    ]
