# Generated by Django 5.0.2 on 2024-02-23 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeatheHistory',
            new_name='WeatherHistory',
        ),
    ]
