# Generated by Django 5.0.2 on 2024-02-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_rename_weathehistory_weatherhistory'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='weatherhistory',
        #     old_name='weather_date',
        #     new_name='created_at',
        # ),
        migrations.AddField(
            model_name='weatherhistory',
            name='date_data',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='humidity',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='latitude',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='longitude',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='real_feel',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='sun_rise',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='sun_set',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='temperature',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='weather_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='wind_speed',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='weatherhistory',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
