# Generated by Django 5.0.2 on 2024-02-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_rename_weather_date_weatherhistory_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weatherhistory',
            name='location day constraint',
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='max_temp',
            field=models.CharField(blank=True, help_text='Maximum Temerature', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='min_temp',
            field=models.CharField(blank=True, help_text='Minimum Temerature', max_length=250, null=True),
        ),

    ]
