# Generated by Django 5.0.2 on 2024-02-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_rename_weather_date_weatherhistory_created_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='weatherhistory',
            constraint=models.UniqueConstraint(fields=('location', 'created_at'), name='location day constraint'),
        ),
    ]
